version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_new
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    